version: "3.2"
services:
  pod-app:
    image: mepemotrarial/pod-app:latest
    ports:
      - 321:80
      - 443:443
  pod-server:
    image: mepemotrarial/pod-server:latest
    ports:
      - 4444:4444
    environment:
      POD_DB_HOST: pod-db
      POD_DB_PASSWORD: password
      POD_SCENARIO_PATH: /data/scenario
      POD_DISABLE_AUTHENTICATION: "true"
      POD_FRONTEND_URL: http://localhost:321
    volumes:
      - .:/data/scenario:ro
    links:
      - pod-db
    entrypoint: ["/bin/sh", "-c"]
    command:
      - node src/app.js
  pod-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "password"
